=== dinaricrypto/sbt-contracts/releases/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Dinari Contract Deployment Metadata",
    "type": "object",
    "definitions": {
        "ChainAddressMap": {
            "type": "object",
            "description": "Chain to Contract Address map in production",
            "propertyNames": {
                "pattern": "^[0-9]*$"
            },
            "additionalProperties": {
                "type": "string",
                "description": "The checksummed address of the token on the specified chain ID",
                "pattern": "^0x[a-fA-F0-9]{40}$"
            }
        }
    },
    "properties": {
        "name": {
            "type": "string",
            "description": "Name of the contract"
        },
        "version": {
            "type": "string",
            "description": "Semantic version of the contract"
        },
        "deployments": {
            "type": "object",
            "properties": {
                "production": {
                    "$ref": "#/definitions/ChainAddressMap"
                },
                "staging": {
                    "$ref": "#/definitions/ChainAddressMap"
                }
            },
            "required": [
                "production",
                "staging"
            ]
        },
        "abi": {
            "type": "array"
        }
    },
    "required": [
        "name",
        "version",
        "deployments",
        "abi"
    ]
}

=== dinaricrypto/sbt-contracts/releases/v1.0.0/wrapped_dshare_beacon.json
{
  "name": "UpgradeableBeacon",
  "version": "1.0.0",
  "deployments": {
    "production": {
      "98866": "0x37d081bF0fCaf8aaf1Df808131187F29bC8Cb29b",
      "98867": "0x37d081bF0fCaf8aaf1Df808131187F29bC8Cb29b"
    },
    "staging": {
      "1": "0xAaB94e1390519bFF1b41E4CdFBF8A4843e636Ec5",
      "7887": "0xAaB94e1390519bFF1b41E4CdFBF8A4843e636Ec5",
      "8453": "0xAaB94e1390519bFF1b41E4CdFBF8A4843e636Ec5",
      "42161": "0xAaB94e1390519bFF1b41E4CdFBF8A4843e636Ec5",
      "81457": "0x68D8d02D15fCB6289D67208a63157B7d1908d169",
      "84532": "0xAaB94e1390519bFF1b41E4CdFBF8A4843e636Ec5",
      "98866": "0x4cdBd5A0938BE8c57DED76880f774db67dc915A9",
      "98867": "0x4fD0e4797b14a212FF10f6e8c6E769B116A4EF4f",
      "421614": "0xAaB94e1390519bFF1b41E4CdFBF8A4843e636Ec5",
      "11155111": "0x68Dd74e23461d99b7312Bfb5baddfd3Fa28404c7",
      "168587773": "0x661CAe699fa0C3D51E2bfd71F37f97fD2eFC3e89"
    }
  },
  "abi": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "implementation_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "initialOwner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "implementation",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "owner",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "renounceOwnership",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "transferOwnership",
      "inputs": [
        {
          "name": "newOwner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "upgradeTo",
      "inputs": [
        {
          "name": "newImplementation",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "OwnershipTransferred",
      "inputs": [
        {
          "name": "previousOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "newOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Upgraded",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "BeaconInvalidImplementation",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "OwnableInvalidOwner",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "OwnableUnauthorizedAccount",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ]
    }
  ]
}

=== dinaricrypto/sbt-contracts/releases/v0.3.1/dshare_beacon.json
{
  "name": "UpgradeableBeacon",
  "version": "0.3.1",
  "deployments": {
    "production": {
      "1": "0x4062d9CbF85da2913880A3A5641cF05E85774f27",
      "11155111": "0x525783cb1f1ABA2FC5dFF884E6510a82704D3274",
      "42161": "0x15436013850211aCf89B656F34b426fdAE01dacb",
      "8453": "0x6Aa1BDa7e764BC62589E64F371A4022B80B3c72a",
      "81457": "0x98C6616F1CC0D3E938A16200830DD55663dd7DD3",
      "7887": "0xa9a60Ccc6363e440eeEaa8Ad015607c7a34360CE",
      "161221135": "0x338e7708C5ee50d08A3fa13D67a569a07c99dF16",
      "98865": "0x0338a3bc52F6F42d1fCD6b6B09Bfd9138A17dbA1"
    },
    "staging": {
      "11155111": "0x58D41009e87c6cD417df629E760Da66c71d057c8",
      "421614": "0x0130A2d1826D42051e19f81884893C5632C5612E",
      "84532": "0xF1755c66eCc50F2bc4230B9A84fE733D4625a72b",
      "168587773": "0xA8d4cF9aED5698e58258a2BdFce42ef74e7e3234",
      "7887": "0x17C477f860aD70541277eF59D5c55aaB0137dbB8",
      "161221135": "0x2E5C088AB4ECD053E0a9ae29195446457143acd6",
      "98864": "0xAe3e76CEaBDc97Cd9697BBa426E1d9323F7B78Ac"
    }
  },
  "abi": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "implementation_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "initialOwner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "implementation",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "owner",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "renounceOwnership",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "transferOwnership",
      "inputs": [
        {
          "name": "newOwner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "upgradeTo",
      "inputs": [
        {
          "name": "newImplementation",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "OwnershipTransferred",
      "inputs": [
        {
          "name": "previousOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "newOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Upgraded",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "BeaconInvalidImplementation",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "OwnableInvalidOwner",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "OwnableUnauthorizedAccount",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ]
    }
  ]
}
