=== dinaricrypto/sbt-contracts/releases/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Dinari Contract Deployment Metadata",
    "type": "object",
    "definitions": {
        "ChainAddressMap": {
            "type": "object",
            "description": "Chain to Contract Address map in production",
            "propertyNames": {
                "pattern": "^[0-9]*$"
            },
            "additionalProperties": {
                "type": "string",
                "description": "The checksummed address of the token on the specified chain ID",
                "pattern": "^0x[a-fA-F0-9]{40}$"
            }
        }
    },
    "properties": {
        "name": {
            "type": "string",
            "description": "Name of the contract"
        },
        "version": {
            "type": "string",
            "description": "Semantic version of the contract"
        },
        "deployments": {
            "type": "object",
            "properties": {
                "production": {
                    "$ref": "#/definitions/ChainAddressMap"
                },
                "staging": {
                    "$ref": "#/definitions/ChainAddressMap"
                }
            },
            "required": [
                "production",
                "staging"
            ]
        },
        "abi": {
            "type": "array"
        }
    },
    "required": [
        "name",
        "version",
        "deployments",
        "abi"
    ]
}

=== dinaricrypto/sbt-contracts/releases/v0.4.3/latest_price_helper.json
{
  "name": "LatestPriceHelper",
  "version": "0.4.3",
  "deployments": {
    "production": {
      "1": "0x761B87Cfab3127af8E6f8A25842e8896aE567af7",
      "11155111": "0x761B87Cfab3127af8E6f8A25842e8896aE567af7",
      "42161": "0x761B87Cfab3127af8E6f8A25842e8896aE567af7",
      "8453": "0x761B87Cfab3127af8E6f8A25842e8896aE567af7",
      "7887": "0x761B87Cfab3127af8E6f8A25842e8896aE567af7",
      "98865": "0x16E2aB73695Caa1E59727d6a9Ec08DfDB790459f"
    },
    "staging": {
      "11155111": "0x761B87Cfab3127af8E6f8A25842e8896aE567af7",
      "421614": "0x761B87Cfab3127af8E6f8A25842e8896aE567af7",
      "98864": "0x94555CC97d3aaC3db095b9f2f8a3240A4003db54"
    }
  },
  "abi": [
    {
      "type": "function",
      "name": "aggregateLatestPriceFromProcessor",
      "inputs": [
        {
          "name": "processor",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "token",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "paymentTokens",
          "type": "address[]",
          "internalType": "address[]"
        }
      ],
      "outputs": [
        {
          "name": "latestPricePoint",
          "type": "tuple",
          "internalType": "struct IOrderProcessor.PricePoint",
          "components": [
            {
              "name": "price",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "blocktime",
              "type": "uint64",
              "internalType": "uint64"
            }
          ]
        }
      ],
      "stateMutability": "view"
    }
  ]
}

=== dinaricrypto/sbt-contracts/releases/v0.3.2/dshare_factory.json
{
  "name": "DShareFactory",
  "version": "0.3.2",
  "deployments": {
    "production": {
      "1": "0x60B5E7eEcb2AEE0382db86491b8cFfA39347c747",
      "11155111": "0x92289a641517BA65438605eF0EeCF5fFB08B597c",
      "42161": "0xB4Ca72eA4d072C779254269FD56093D3ADf603b8",
      "81457": "0x6Aa1BDa7e764BC62589E64F371A4022B80B3c72a"
    },
    "staging": {
      "11155111": "0x9C0d82875c7C8482F9B9f15dd26303D746F47B89",
      "421614": "0x8A9b764204098AfF161A34353dC835bf5BB49Ce4",
      "168587773": "0xfd7681D09067451a34991A1c84ec98d57262cf5e"
    }
  },
  "abi": [
    {
      "type": "constructor",
      "inputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "UPGRADE_INTERFACE_VERSION",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "announceExistingDShare",
      "inputs": [
        {
          "name": "dShare",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "wrappedDShare",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "createDShare",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "name",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "symbol",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "wrappedName",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "wrappedSymbol",
          "type": "string",
          "internalType": "string"
        }
      ],
      "outputs": [
        {
          "name": "dShare",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "wrappedDShare",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "getDShareBeacon",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getDShares",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address[]",
          "internalType": "address[]"
        },
        {
          "name": "",
          "type": "address[]",
          "internalType": "address[]"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getTransferRestrictor",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getWrappedDShareBeacon",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "initialize",
      "inputs": [
        {
          "name": "_owner",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "_dShareBeacon",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "_wrappedDShareBeacon",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "_transferRestrictor",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "owner",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "proxiableUUID",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "renounceOwnership",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "setNewTransferRestrictor",
      "inputs": [
        {
          "name": "_transferRestrictor",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "transferOwnership",
      "inputs": [
        {
          "name": "newOwner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "upgradeToAndCall",
      "inputs": [
        {
          "name": "newImplementation",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "data",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "outputs": [],
      "stateMutability": "payable"
    },
    {
      "type": "event",
      "name": "DShareAdded",
      "inputs": [
        {
          "name": "dShare",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "wrappedDShare",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "symbol",
          "type": "string",
          "indexed": true,
          "internalType": "string"
        },
        {
          "name": "name",
          "type": "string",
          "indexed": false,
          "internalType": "string"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Initialized",
      "inputs": [
        {
          "name": "version",
          "type": "uint64",
          "indexed": false,
          "internalType": "uint64"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "NewTransferRestrictorSet",
      "inputs": [
        {
          "name": "transferRestrictor",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "OwnershipTransferred",
      "inputs": [
        {
          "name": "previousOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "newOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Upgraded",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "AddressEmptyCode",
      "inputs": [
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "ERC1967InvalidImplementation",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "ERC1967NonPayable",
      "inputs": []
    },
    {
      "type": "error",
      "name": "FailedInnerCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidInitialization",
      "inputs": []
    },
    {
      "type": "error",
      "name": "Mismatch",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NotInitializing",
      "inputs": []
    },
    {
      "type": "error",
      "name": "OwnableInvalidOwner",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "OwnableUnauthorizedAccount",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "PreviouslyAnnounced",
      "inputs": []
    },
    {
      "type": "error",
      "name": "UUPSUnauthorizedCallContext",
      "inputs": []
    },
    {
      "type": "error",
      "name": "UUPSUnsupportedProxiableUUID",
      "inputs": [
        {
          "name": "slot",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ]
    },
    {
      "type": "error",
      "name": "ZeroAddress",
      "inputs": []
    }
  ]
}

=== dinaricrypto/sbt-contracts/releases/v0.3.1/wrapped_dshare_beacon.json
{
  "name": "UpgradeableBeacon",
  "version": "0.3.1",
  "deployments": {
    "production": {
      "1": "0x5CCB5482dc15aAdd36d6c02C0d44ce0E3e7E6835",
      "11155111": "0xa5D5F87DA8B58Bd41514754738fAE4C8c4419FB0",
      "42161": "0xad20601C7a3212c7BbF2ACdFEDBAD99d803bC7F5",
      "8453": "0x9B3e9d3Fb6849c9F0eDcB2A9EbB6Af83B7817DE5",
      "81457": "0xe1B2FEEDE3ffE7e63a89A669A08688951c94611e",
      "7887": "0xd1d93E6Ad5219083Bb2cf3B065a562223381b71F",
      "161221135": "0x94E0555B92E3907f6598b68Bc82c33079C8850Af",
      "98865": "0xff86Bc594940A9A9f81E60d9E76913cb3B45a3E5"
    },
    "staging": {
      "11155111": "0x7ec1f2ecf4d194AEe4992834Fd921782e3828bb7",
      "421614": "0x23FE2f04727d363F5b5969728e1DF0d2f4b15d2e",
      "84532": "0x6Bb0Ec10dCEF7Ac0f5Fe7f8a15d43A2e83a2FeB1",
      "168587773": "0x22098564c1C27A13e2966805330e5DfcC9C7f10D",
      "7887": "0x2e92D8Ba4122a40922BE2B46E01982749d8FC127",
      "161221135": "0xA8d4cF9aED5698e58258a2BdFce42ef74e7e3234",
      "98864": "0x17Fd817B130F28eAEE17E4da7BD2a12296342390"
    }
  },
  "abi": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "implementation_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "initialOwner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "implementation",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "owner",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "renounceOwnership",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "transferOwnership",
      "inputs": [
        {
          "name": "newOwner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "upgradeTo",
      "inputs": [
        {
          "name": "newImplementation",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "OwnershipTransferred",
      "inputs": [
        {
          "name": "previousOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "newOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Upgraded",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "BeaconInvalidImplementation",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "OwnableInvalidOwner",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "OwnableUnauthorizedAccount",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ]
    }
  ]
}

=== dinaricrypto/sbt-contracts/releases/v0.1.0/token_lock_check.json
{
  "name": "TokenLockCheck",
  "version": "0.1.0",
  "deployments": {
    "production": {
      "1": "0xc63ac73EcD95a2D6Cb313757378D6c16c760e712",
      "11155111": "0xDE9925851f41B4A405f7C8A44DdaB399D861dC5b",
      "42161": "0x57591E07eAB6c2B3BeE529586253217584316B2B",
      "81457": "0x7e599C828C42758be0A6336DC32334b8AFB6A8FC"
    },
    "staging": {
      "11155111": "0xB12CC65B851F892934285E6f603ac8eeb48793AA",
      "421614": "0x0835bA5A91bbF9c146d18208B8E8Cc4E70198f5e",
      "161221135": "0x50d0A27B24423D27c8dba04213cd22f2Aa067683"
    }
  },
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "usdc",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "usdt",
          "type": "address"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "inputs": [],
      "name": "NotContract",
      "type": "error"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "previousOwner",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "newOwner",
          "type": "address"
        }
      ],
      "name": "OwnershipTransferred",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "name": "callSelector",
      "outputs": [
        {
          "internalType": "bytes4",
          "name": "",
          "type": "bytes4"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "token",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "isTransferLocked",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "owner",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "renounceOwnership",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "token",
          "type": "address"
        }
      ],
      "name": "setAsDShare",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "token",
          "type": "address"
        },
        {
          "internalType": "bytes4",
          "name": "selector",
          "type": "bytes4"
        }
      ],
      "name": "setCallSelector",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "newOwner",
          "type": "address"
        }
      ],
      "name": "transferOwnership",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ]
}

=== dinaricrypto/sbt-contracts/releases/v0.3.3/unity_oracle.json
{
  "name": "UnityOracle",
  "version": "0.3.3",
  "deployments": {
    "production": {
      "1": "0x942AB403B2e20a5a9940eE9Cb073e5850B04330F",
      "42161": "0x6a05Db7bdab407Bc80D4A09bA8A22de303bAe81A"
    },
    "staging": {
      "11155111": "0x1E6F58EEE791a41D79855840B8d382Fb564Ff377",
      "421614": "0xc92aA0cB8910b9B4673D75E5C27C14eEeFBee5b6",
      "161221135": "0x100b5E7983730b8bF07361210d7a7e125CaC8ac5"
    }
  },
  "abi": [
    {
      "type": "function",
      "name": "decimals",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint8",
          "internalType": "uint8"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "description",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "getRoundData",
      "inputs": [
        {
          "name": "",
          "type": "uint80",
          "internalType": "uint80"
        }
      ],
      "outputs": [
        {
          "name": "roundId",
          "type": "uint80",
          "internalType": "uint80"
        },
        {
          "name": "answer",
          "type": "int256",
          "internalType": "int256"
        },
        {
          "name": "startedAt",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "updatedAt",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "answeredInRound",
          "type": "uint80",
          "internalType": "uint80"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "latestRoundData",
      "inputs": [],
      "outputs": [
        {
          "name": "roundId",
          "type": "uint80",
          "internalType": "uint80"
        },
        {
          "name": "answer",
          "type": "int256",
          "internalType": "int256"
        },
        {
          "name": "startedAt",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "updatedAt",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "answeredInRound",
          "type": "uint80",
          "internalType": "uint80"
        }
      ],
      "stateMutability": "pure"
    },
    {
      "type": "function",
      "name": "version",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "pure"
    }
  ]
}

=== dinaricrypto/sbt-contracts/releases/v1.0.0/dshare_beacon.json
{
  "name": "UpgradeableBeacon",
  "version": "1.0.0",
  "deployments": {
    "production": {
      "98866": "0xF4950A31566cDBA1140058178e1AA3eC8afF3228",
      "98867": "0xF4950A31566cDBA1140058178e1AA3eC8afF3228"
    },
    "staging": {
      "1": "0x4F597f4457B24695BC72c42302d4493050ADeE46",
      "7887": "0x4F597f4457B24695BC72c42302d4493050ADeE46",
      "8453": "0x4F597f4457B24695BC72c42302d4493050ADeE46",
      "42161": "0x4F597f4457B24695BC72c42302d4493050ADeE46",
      "81457": "0x9381c0e2EF8F6e8B216819b3eF04E73cdD783D4c",
      "84532": "0x4F597f4457B24695BC72c42302d4493050ADeE46",
      "98866": "0xAaB94e1390519bFF1b41E4CdFBF8A4843e636Ec5",
      "98867": "0x5405C077b4f15132039891545B224cEF90483809",
      "421614": "0x4F597f4457B24695BC72c42302d4493050ADeE46",
      "11155111": "0xf141B07Fb838c4a59334715B4464878EB25E9E60",
      "168587773": "0x68D8d02D15fCB6289D67208a63157B7d1908d169"
    }
  },
  "abi": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "implementation_",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "initialOwner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "implementation",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "owner",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "renounceOwnership",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "transferOwnership",
      "inputs": [
        {
          "name": "newOwner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "upgradeTo",
      "inputs": [
        {
          "name": "newImplementation",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "OwnershipTransferred",
      "inputs": [
        {
          "name": "previousOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "newOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Upgraded",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "BeaconInvalidImplementation",
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "OwnableInvalidOwner",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "OwnableUnauthorizedAccount",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ]
    }
  ]
}
